name: time_counter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  dio: ^5.4.1
  flick_video_player: ^0.7.0
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  vimeo_video_player: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
